---@meta
-- Cosmo Lua documentation overrides

--- Sends an HTTP/HTTPS request to the specified URL.
---
--- If only URL is provided, sends a GET request.
--- If body is a string, sends a POST request.
--- If body is a table, uses the specified options.
---
--- Options (table fields):
---
--- - `method` (default: "GET"): HTTP method, converted to uppercase.
---
--- - `body` (default: ""): Request body to send.
---
--- - `headers` (table): Custom headers as {name=value, ...}.
---
--- - `followredirect` (default: true): Follow 3xx redirects.
---
--- - `maxredirects` (default: 5): Maximum redirects before returning.
---
--- - `keepalive` (boolean|table): Reuse connections to same host.
---   Disabled for HTTPS. Pass a table to store socket mappings
---   across calls. Set table.close=true to close after request.
---
--- - `proxy` (string): HTTP proxy URL, e.g. "http://proxy:8080".
---   Supports authentication: "http://user:pass@proxy:8080".
---   Falls back to http_proxy/HTTP_PROXY environment variables.
---
--- - `maxresponse` (default: 104857600): Maximum response size in bytes.
---
--- - `resettls` (default: true): Reset TLS state after fork.
---
--- On redirect, method and body are preserved except for 303 (See Other),
--- which converts to GET with no body.
---
--- Returns status, headers table, and body string on success.
--- Returns nil and error string on failure.
---
---@param url string URL to fetch
---@param body? string|table request body or options table
---@return integer status HTTP status code
---@return table headers response headers
---@return string body response body
---@overload fun(url: string, body?: string|table): nil, error: string
function Fetch(url, body) end

---@param url string URL to fetch
---@param body? string|table request body or options table
---@return integer status HTTP status code
---@return table headers response headers
---@return string body response body
---@overload fun(url: string, body?: string|table): nil, error: string
function cosmo.Fetch(url, body) end
