---@meta
-- Cosmo Lua documentation overrides

---@class cosmo
cosmo = {}

--- Sends an HTTP/HTTPS request to the specified URL.
---
--- If only URL is provided, sends a GET request.
--- If body is a string, sends a POST request.
--- If body is a table, uses the specified options.
---
--- Options (table fields):
---
--- - `method` (default: "GET"): HTTP method, converted to uppercase.
---
--- - `body` (default: ""): Request body to send.
---
--- - `headers` (table): Custom headers as {name=value, ...}.
---
--- - `followredirect` (default: true): Follow 3xx redirects.
---
--- - `maxredirects` (default: 5): Maximum redirects before returning.
---
--- - `keepalive` (boolean|table): Reuse connections to same host.
---   Disabled for HTTPS. Pass a table to store socket mappings
---   across calls. Set table.close=true to close after request.
---
--- Cosmo additions:
---
--- - `proxy` (string): HTTP proxy URL, e.g. "http://proxy:8080".
---   Supports Basic authentication: "http://user:pass@proxy:8080".
---
--- - `maxresponse` (default: 104857600): Maximum response size in bytes.
---   Protects against memory exhaustion from large responses.
---
--- - `resettls` (default: true): Reset TLS state after fork.
---   Ensures child processes get fresh DRBG entropy.
---
--- Environment variables:
---
--- - `http_proxy` / `HTTP_PROXY`: Default proxy URL when `proxy` option
---   is not specified. Supports same format as the option.
---
--- - `SSL_CERT_FILE`: Path to CA certificate bundle file for TLS verification.
---   Overrides default system CA locations.
---
--- - `SSL_NO_SYSTEM_CERTS`: If set, skip loading system CA certificates.
---   Only embedded certificates will be used.
---
--- On redirect, method and body are preserved except for 303 (See Other),
--- which converts to GET with no body.
---
--- Returns status, headers table, and body string on success.
--- Returns nil and error string on failure.
---
---@param url string URL to fetch
---@param body? string|table request body or options table
---@return integer status HTTP status code
---@return table headers response headers
---@return string body response body
---@overload fun(url: string, body?: string|table): nil, error: string
function Fetch(url, body) end

---@param url string URL to fetch
---@param body? string|table request body or options table
---@return integer status HTTP status code
---@return table headers response headers
---@return string body response body
---@overload fun(url: string, body?: string|table): nil, error: string
function cosmo.Fetch(url, body) end
